- ansible.builtin.import_playbook: repos_distro_au.yml

- hosts: localhost
  gather_facts: yes

  vars:
    - my_name: "service_slurm_login"
    - my_packages_deb:
      - munge
      - slurm-client
      - nfs-common
      - nfs-kernel-server

  tasks:

  - name: "{{ my_name }} install packages"
    ansible.builtin.apt:
      name: "{{ my_packages_deb }}"
      state: latest
      update_cache: true

  - name: "{{ my_name }} /var/spool/slurmd path"
    ansible.builtin.file:
      path: "/var/spool/slurmd"
      state: directory
      recurse: true
      owner: "slurm"
      group: "slurm"

  - name: "{{ my_name }} /var/log/slurm path"
    ansible.builtin.file:
      path: "/var/log/slurm"
      state: directory
      recurse: true
      owner: "slurm"
      group: "slurm"

  - name: "{{ my_name }} slurm.conf"
    ansible.builtin.template:
      src: "templates/{{ my_name }}/slurm.conf.j2"
      dest: "/etc/slurm/slurm.conf"
      owner: "slurm"
      group: "slurm"
      mode: 0644
